
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/nav/NavBar";
import Footer from "./components/footer/Footer";
import { CartContextProvider } from "./context/CartContext";// ✔ Correct path

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-commerce | Flipkart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} text-slate-700`}>

        {/* ✔ Entire app wrapped inside CartContext */}
        <CartContextProvider>
          <div className="flex flex-col min-h-screen border">
            <NavBar />
            <main className="grow">{children}</main>
            <Footer />
          </div>
        </CartContextProvider>

      </body>
    </html>
  );
}
